### ISSUE TITLE
Does not compile using rustc on ubuntu 20.04

### ISSUE THREAD

**Issue by pankajd-57** [itkovian/sarchive#102]
How to compile and install ob ubuntu 20.04?
root@server1:/opt/archive/sarchive-production/src# rustc  main.rs
error[E0463]: can't find crate for `chrono`
  --> monitor.rs:22:1
   |
22 | extern crate chrono;
   | ^^^^^^^^^^^^^^^^^^^^ can't find crate

error[E0463]: can't find crate for `crossbeam_channel`
  --> monitor.rs:23:1
   |
23 | extern crate crossbeam_channel;
   | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ can't find crate

error[E0463]: can't find crate for `crossbeam_utils`
  --> monitor.rs:24:1
   |
24 | extern crate crossbeam_utils;
   | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ can't find crate

error: environment variable `CARGO_PKG_VERSION` not defined
  --> main.rs:48:23
   |
48 | const VERSION: &str = env!("CARGO_PKG_VERSION");
   |                       ^^^^^^^^^^^^^^^^^^^^^^^^^
   |
   = note: this error originates in the macro `env` (in Nightly builds, run with -Z macro-backtrace for more info)

error[E0432]: unresolved import `clap`
  --> main.rs:23:5

**Comment by itkovian** [comment]
Sorry for answering so late. 

Are you still running into this issue?
